### ISSUE TITLE
Blocking Error

### ISSUE THREAD

**Issue by Cloud-and-Proud** [ixanza/synOblivionInteractionIcons#2]
Hej, I'm getting this error, what do I do?

dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.

**Comment by ixanza** [comment]
It seems you're missing dotnet 6.0 sdk

https://dotnet.microsoft.com/en-us/download

grab the x64 sdk for 6.0

**Comment by Cloud-and-Proud** [comment]
Thanks!
