### ISSUE TITLE
Oblivion Interactions Icons 1.3 changed the name of the esl, causing a blocking error

### ISSUE THREAD

**Issue by xcfrg** [ixanza/synOblivionInteractionIcons#3]
The name of the ESL has changed: 
![image](https://user-images.githubusercontent.com/30675315/151712535-b5276993-3a50-46a4-ac26-1aaab224d069.png)

**Comment by cacodemonkey** [comment]
version 1.1 and later are using the patcher at https://github.com/cacodemonkey/synOblivionInteractionIcons .
